# Generated by Django 5.1.4 on 2026-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cmspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='coworking_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='coworking_hours_closed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='office_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='office_hours_closed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='phone_3',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
