# Generated by Django 5.1.4 on 2026-09-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facilities/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_images', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility images',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('facility',), name='unique_primary_image_per_facility')],
            },
        ),
    ]
